In [25]:
import pandas as pd
import os

# Đường dẫn
RAW_DIR = '../data/raw/'
PROCESSED_DIR = '../data/processed/'

In [26]:
sales     = pd.read_csv(os.path.join(RAW_DIR, 'sales.csv'), parse_dates=['Date'])
sales = sales.dropna()

traffic   = pd.read_csv(os.path.join(RAW_DIR, 'web_traffic.csv'), parse_dates=['date'])
traffic = traffic.dropna()

shipment  = pd.read_csv(os.path.join(RAW_DIR, 'shipments.csv'), parse_dates=['ship_date', 'delivery_date'])
shipment = shipment.dropna()

review  = pd.read_csv(os.path.join(RAW_DIR, 'reviews.csv'), parse_dates=['review_date'])
review = review.dropna()

returns = pd.read_csv(os.path.join(RAW_DIR, 'returns.csv'), parse_dates=['return_date'])
returns = returns.dropna()

customer = pd.read_csv(os.path.join(RAW_DIR, 'customers.csv'), parse_dates=['signup_date'])
customer = customer.dropna()

inventory = pd.read_csv(os.path.join(RAW_DIR, 'inventory.csv'), parse_dates=['snapshot_date'])
inventory = inventory.dropna()

orders = pd.read_csv(os.path.join(RAW_DIR, 'orders.csv'), parse_dates=['order_date'])
orders= orders.dropna()

In [27]:
# File mẫu để làm khung cho tập Test
test_df   = pd.read_csv(os.path.join(RAW_DIR, 'sample_submission.csv'), parse_dates=['Date'])

In [28]:
# 2. Gom dữ liệu theo ngày (order_date)
# Giả sử bảng orders có cột 'order_id' và 'total_amount'
daily_orders = orders.groupby('order_date').agg({
    'order_id': 'nunique',       
    'customer_id': 'nunique'   
           
}).reset_index()

daily_orders = daily_orders.rename(columns={
    'order_id': 'number_of_order',
    'customer_id': 'number_of_customer'
})

daily_orders

     order_date  number_of_order  number_of_customer
0    2012-07-04              162                 161
1    2012-07-05               97                  97
2    2012-07-06               93                  93
3    2012-07-07               73                  73
4    2012-07-08               88                  87
...         ...              ...                 ...
3828 2022-12-27              108                 107
3829 2022-12-28              164                 163
3830 2022-12-29              143                 143
3831 2022-12-30              106                 106
3832 2022-12-31               74                  74

[3833 rows x 3 columns]

In [29]:
daily_sales = sales.groupby('Date').agg({
    'Revenue': 'sum',       
    'COGS': 'sum'    
           
}).reset_index()


daily_sales

           Date     Revenue        COGS
0    2012-07-04  5123547.94  3982991.19
1    2012-07-05  2751773.45  2150580.23
2    2012-07-06  3054029.42  2517632.84
3    2012-07-07  2667930.94  2108246.62
4    2012-07-08  2360851.90  1808622.79
...         ...         ...         ...
3828 2022-12-27  2100553.66  2184872.24
3829 2022-12-28  3448729.20  3513621.00
3830 2022-12-29  3083944.33  3170787.10
3831 2022-12-30  2884668.76  3022292.15
3832 2022-12-31  2383037.48  2279288.13

[3833 rows x 3 columns]

In [30]:
daily_traffic = traffic.groupby('date').agg({
    'sessions': 'sum',       
    'page_views': 'sum'
           
}).reset_index()


daily_traffic = daily_traffic.rename(columns={
    
    'sessions': 'sum_of_sessions',
    'page_views': 'sum_of_page_views'
})

daily_traffic

           date  sum_of_sessions  sum_of_page_views
0    2013-01-01             9760              39093
1    2013-01-02            10456              47611
2    2013-01-03            10076              36963
3    2013-01-04             9973              53078
4    2013-01-05            10223              36790
...         ...              ...                ...
3647 2022-12-27            17416              62527
3648 2022-12-28            21071              67456
3649 2022-12-29            20884              82155
3650 2022-12-30            17679              79308
3651 2022-12-31            21743              94844

[3652 rows x 3 columns]

In [31]:
daily_shipment = shipment.groupby('ship_date').agg({
    'shipping_fee': 'sum',       
        
}).reset_index()

daily_shipment = daily_shipment.rename(columns={

    'shipping_fee': 'sum_of_shipping_fee'
})

daily_shipment

      ship_date  sum_of_shipping_fee
0    2012-07-04               157.76
1    2012-07-05               172.75
2    2012-07-06               292.15
3    2012-07-07               328.58
4    2012-07-08               428.18
...         ...                  ...
3826 2022-12-25               447.13
3827 2022-12-26               400.97
3828 2022-12-27               256.63
3829 2022-12-28               202.67
3830 2022-12-29               211.90

[3831 rows x 2 columns]

In [32]:
daily_review = review.groupby('review_date').agg({      
    'customer_id': 'nunique',    
    'rating'     : 'mean'    
}).reset_index()

daily_review = daily_review.rename(columns={
    
    'customer_id': 'number_visitor_review',
    'rating': 'mean_of_rating'
})

daily_review

     review_date  number_visitor_review  mean_of_rating
0     2012-07-10                      1        5.000000
1     2012-07-12                      1        5.000000
2     2012-07-13                      2        4.500000
3     2012-07-14                      2        3.500000
4     2012-07-15                      4        4.250000
...          ...                    ...             ...
3820  2022-12-27                      9        4.111111
3821  2022-12-28                      6        4.333333
3822  2022-12-29                     10        3.700000
3823  2022-12-30                     18        4.166667
3824  2022-12-31                     18        3.833333

[3825 rows x 3 columns]

In [33]:
daily_returns = returns.groupby('return_date').agg({

    'refund_amount' : 'sum'   
           
}).reset_index()

daily_returns = daily_returns.rename(columns={
    'refund_amount': 'sum_of_refund',
   
})

daily_returns

     return_date  sum_of_refund
0     2012-07-11        6493.75
1     2012-07-12        4834.00
2     2012-07-14       52967.00
3     2012-07-15       13534.62
4     2012-07-16       16170.54
...          ...            ...
3801  2022-12-27       26482.11
3802  2022-12-28       97387.35
3803  2022-12-29       20897.84
3804  2022-12-30       43613.12
3805  2022-12-31       97557.23

[3806 rows x 2 columns]

In [34]:
daily_customer = customer.groupby('signup_date').agg({
    'customer_id': 'nunique',        
           
}).reset_index()

daily_customer = daily_customer.rename(columns={
    
    'customer_id': 'number_of_customer_signup'
})

daily_customer

     signup_date  number_of_customer_signup
0     2012-01-17                          1
1     2012-01-20                          1
2     2012-02-02                          1
3     2012-02-05                          1
4     2012-02-07                          1
...          ...                        ...
3936  2022-12-27                         60
3937  2022-12-28                         65
3938  2022-12-29                         66
3939  2022-12-30                         51
3940  2022-12-31                         61

[3941 rows x 2 columns]

In [35]:
daily_inventory = inventory.groupby('snapshot_date').agg({
    'stock_on_hand': 'sum',
    'units_sold': 'sum',   
    'units_received': 'sum'     
           
}).reset_index()

daily_inventory

    snapshot_date  stock_on_hand  units_sold  units_received
0      2012-07-31          23698        7451            8796
1      2012-08-31          26249        9983           11799
2      2012-09-30          27519        7303            8552
3      2012-10-31          29194        6622            7732
4      2012-11-30          30134        6251            7276
..            ...            ...         ...             ...
121    2022-08-31         104884        4772            5499
122    2022-09-30         107309        3360            3868
123    2022-10-31         104255        2908            3309
124    2022-11-30          95003        2332            2649
125    2022-12-31         104235        3565            4081

[126 rows x 4 columns]

In [36]:
master_df = daily_sales.merge(daily_orders, left_on='Date',right_on= 'order_date',  how='left')
master_df = master_df.drop('order_date', axis=1)
master_df

           Date     Revenue        COGS  number_of_order  number_of_customer
0    2012-07-04  5123547.94  3982991.19              162                 161
1    2012-07-05  2751773.45  2150580.23               97                  97
2    2012-07-06  3054029.42  2517632.84               93                  93
3    2012-07-07  2667930.94  2108246.62               73                  73
4    2012-07-08  2360851.90  1808622.79               88                  87
...         ...         ...         ...              ...                 ...
3828 2022-12-27  2100553.66  2184872.24              108                 107
3829 2022-12-28  3448729.20  3513621.00              164                 163
3830 2022-12-29  3083944.33  3170787.10              143                 143
3831 2022-12-30  2884668.76  3022292.15              106                 106
3832 2022-12-31  2383037.48  2279288.13               74                  74

[3833 rows x 5 columns]

In [37]:
# Chuyển đổi toàn bộ cột Date sang datetime
master_df['Date'] = pd.to_datetime(master_df['Date'])

# Bây giờ mới thêm cột month
master_df['month'] = master_df['Date'].dt.month

In [38]:
master_df = master_df.merge(daily_traffic, left_on='Date', right_on='date', how = 'left')
master_df = master_df.drop('date', axis=1)
master_df

,Date,Revenue,COGS,number_of_order,number_of_customer,month,sum_of_sessions,sum_of_page_views
0,2012-07-04,5123547.94,3982991.19,162,161,7,NaN,NaN
1,2012-07-05,2751773.45,2150580.23,97,97,7,NaN,NaN
2,2012-07-06,3054029.42,2517632.84,93,93,7,NaN,NaN
3,2012-07-07,2667930.94,2108246.62,73,73,7,NaN,NaN
4,2012-07-08,2360851.90,1808622.79,88,87,7,NaN,NaN
...,...,...,...,...,...,...,...,...
3828,2022-12-27,2100553.66,2184872.24,108,107,12,17416.0,62527.0
3829,2022-12-28,3448729.20,3513621.00,164,163,12,21071.0,67456.0
3830,2022-12-29,3083944.33,3170787.10,143,143,12,20884.0,82155.0
3831,2022-12-30,2884668.76,3022292.15,106,106,12,17679.0,79308.0
3832,2022-12-31,2383037.48,2279288.13,74,74,12,21743.0,94844.0

In [39]:
master_df = master_df.merge(daily_shipment, left_on='Date', right_on='ship_date', how = 'left')
master_df = master_df.drop('ship_date', axis=1)
master_df

,Date,Revenue,COGS,number_of_order,number_of_customer,month,sum_of_sessions,sum_of_page_views,sum_of_shipping_fee
0,2012-07-04,5123547.94,3982991.19,162,161,7,NaN,NaN,157.76
1,2012-07-05,2751773.45,2150580.23,97,97,7,NaN,NaN,172.75
2,2012-07-06,3054029.42,2517632.84,93,93,7,NaN,NaN,292.15
3,2012-07-07,2667930.94,2108246.62,73,73,7,NaN,NaN,328.58
4,2012-07-08,2360851.90,1808622.79,88,87,7,NaN,NaN,428.18
...,...,...,...,...,...,...,...,...,...
3828,2022-12-27,2100553.66,2184872.24,108,107,12,17416.0,62527.0,256.63
3829,2022-12-28,3448729.20,3513621.00,164,163,12,21071.0,67456.0,202.67
3830,2022-12-29,3083944.33,3170787.10,143,143,12,20884.0,82155.0,211.90
3831,2022-12-30,2884668.76,3022292.15,106,106,12,17679.0,79308.0,NaN
3832,2022-12-31,2383037.48,2279288.13,74,74,12,21743.0,94844.0,NaN

In [40]:
master_df = master_df.merge(daily_review, left_on='Date', right_on='review_date', how = 'left')
master_df

,Date,Revenue,COGS,number_of_order,number_of_customer,month,sum_of_sessions,sum_of_page_views,sum_of_shipping_fee,review_date,number_visitor_review,mean_of_rating
0,2012-07-04,5123547.94,3982991.19,162,161,7,NaN,NaN,157.76,NaT,NaN,NaN
1,2012-07-05,2751773.45,2150580.23,97,97,7,NaN,NaN,172.75,NaT,NaN,NaN
2,2012-07-06,3054029.42,2517632.84,93,93,7,NaN,NaN,292.15,NaT,NaN,NaN
3,2012-07-07,2667930.94,2108246.62,73,73,7,NaN,NaN,328.58,NaT,NaN,NaN
4,2012-07-08,2360851.90,1808622.79,88,87,7,NaN,NaN,428.18,NaT,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3828,2022-12-27,2100553.66,2184872.24,108,107,12,17416.0,62527.0,256.63,2022-12-27,9.0,4.111111
3829,2022-12-28,3448729.20,3513621.00,164,163,12,21071.0,67456.0,202.67,2022-12-28,6.0,4.333333
3830,2022-12-29,3083944.33,3170787.10,143,143,12,20884.0,82155.0,211.90,2022-12-29,10.0,3.700000
3831,2022-12-30,2884668.76,3022292.15,106,106,12,17679.0,79308.0,NaN,2022-12-30,18.0,4.166667
3832,2022-12-31,2383037.48,2279288.13,74,74,12,21743.0,94844.0,NaN,2022-12-31,18.0,3.833333

In [41]:
master_df = master_df.drop('review_date', axis=1)
master_df

,Date,Revenue,COGS,number_of_order,number_of_customer,month,sum_of_sessions,sum_of_page_views,sum_of_shipping_fee,number_visitor_review,mean_of_rating
0,2012-07-04,5123547.94,3982991.19,162,161,7,NaN,NaN,157.76,NaN,NaN
1,2012-07-05,2751773.45,2150580.23,97,97,7,NaN,NaN,172.75,NaN,NaN
2,2012-07-06,3054029.42,2517632.84,93,93,7,NaN,NaN,292.15,NaN,NaN
3,2012-07-07,2667930.94,2108246.62,73,73,7,NaN,NaN,328.58,NaN,NaN
4,2012-07-08,2360851.90,1808622.79,88,87,7,NaN,NaN,428.18,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
3828,2022-12-27,2100553.66,2184872.24,108,107,12,17416.0,62527.0,256.63,9.0,4.111111
3829,2022-12-28,3448729.20,3513621.00,164,163,12,21071.0,67456.0,202.67,6.0,4.333333
3830,2022-12-29,3083944.33,3170787.10,143,143,12,20884.0,82155.0,211.90,10.0,3.700000
3831,2022-12-30,2884668.76,3022292.15,106,106,12,17679.0,79308.0,NaN,18.0,4.166667
3832,2022-12-31,2383037.48,2279288.13,74,74,12,21743.0,94844.0,NaN,18.0,3.833333

In [42]:
master_df = master_df.merge(daily_returns, left_on='Date', right_on='return_date', how = 'left')
master_df

,Date,Revenue,COGS,number_of_order,number_of_customer,month,sum_of_sessions,sum_of_page_views,sum_of_shipping_fee,number_visitor_review,mean_of_rating,return_date,sum_of_refund
0,2012-07-04,5123547.94,3982991.19,162,161,7,NaN,NaN,157.76,NaN,NaN,NaT,NaN
1,2012-07-05,2751773.45,2150580.23,97,97,7,NaN,NaN,172.75,NaN,NaN,NaT,NaN
2,2012-07-06,3054029.42,2517632.84,93,93,7,NaN,NaN,292.15,NaN,NaN,NaT,NaN
3,2012-07-07,2667930.94,2108246.62,73,73,7,NaN,NaN,328.58,NaN,NaN,NaT,NaN
4,2012-07-08,2360851.90,1808622.79,88,87,7,NaN,NaN,428.18,NaN,NaN,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3828,2022-12-27,2100553.66,2184872.24,108,107,12,17416.0,62527.0,256.63,9.0,4.111111,2022-12-27,26482.11
3829,2022-12-28,3448729.20,3513621.00,164,163,12,21071.0,67456.0,202.67,6.0,4.333333,2022-12-28,97387.35
3830,2022-12-29,3083944.33,3170787.10,143,143,12,20884.0,82155.0,211.90,10.0,3.700000,2022-12-29,20897.84
3831,2022-12-30,2884668.76,3022292.15,106,106,12,17679.0,79308.0,NaN,18.0,4.166667,2022-12-30,43613.12
3832,2022-12-31,2383037.48,2279288.13,74,74,12,21743.0,94844.0,NaN,18.0,3.833333,2022-12-31,97557.23

In [43]:
master_df = master_df.merge(daily_customer, left_on='Date', right_on='signup_date', how = 'left')
master_df

,Date,Revenue,COGS,number_of_order,number_of_customer,month,sum_of_sessions,sum_of_page_views,sum_of_shipping_fee,number_visitor_review,mean_of_rating,return_date,sum_of_refund,signup_date,number_of_customer_signup
0,2012-07-04,5123547.94,3982991.19,162,161,7,NaN,NaN,157.76,NaN,NaN,NaT,NaN,2012-07-04,3.0
1,2012-07-05,2751773.45,2150580.23,97,97,7,NaN,NaN,172.75,NaN,NaN,NaT,NaN,2012-07-05,5.0
2,2012-07-06,3054029.42,2517632.84,93,93,7,NaN,NaN,292.15,NaN,NaN,NaT,NaN,NaT,NaN
3,2012-07-07,2667930.94,2108246.62,73,73,7,NaN,NaN,328.58,NaN,NaN,NaT,NaN,2012-07-07,4.0
4,2012-07-08,2360851.90,1808622.79,88,87,7,NaN,NaN,428.18,NaN,NaN,NaT,NaN,2012-07-08,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3828,2022-12-27,2100553.66,2184872.24,108,107,12,17416.0,62527.0,256.63,9.0,4.111111,2022-12-27,26482.11,2022-12-27,60.0
3829,2022-12-28,3448729.20,3513621.00,164,163,12,21071.0,67456.0,202.67,6.0,4.333333,2022-12-28,97387.35,2022-12-28,65.0
3830,2022-12-29,3083944.33,3170787.10,143,143,12,20884.0,82155.0,211.90,10.0,3.700000,2022-12-29,20897.84,2022-12-29,66.0
3831,2022-12-30,2884668.76,3022292.15,106,106,12,17679.0,79308.0,NaN,18.0,4.166667,2022-12-30,43613.12,2022-12-30,51.0
3832,2022-12-31,2383037.48,2279288.13,74,74,12,21743.0,94844.0,NaN,18.0,3.833333,2022-12-31,97557.23,2022-12-31,61.0

In [44]:
master_df = master_df.drop('return_date', axis=1)
master_df = master_df.drop('signup_date', axis=1)

master_df

,Date,Revenue,COGS,number_of_order,number_of_customer,month,sum_of_sessions,sum_of_page_views,sum_of_shipping_fee,number_visitor_review,mean_of_rating,sum_of_refund,number_of_customer_signup
0,2012-07-04,5123547.94,3982991.19,162,161,7,NaN,NaN,157.76,NaN,NaN,NaN,3.0
1,2012-07-05,2751773.45,2150580.23,97,97,7,NaN,NaN,172.75,NaN,NaN,NaN,5.0
2,2012-07-06,3054029.42,2517632.84,93,93,7,NaN,NaN,292.15,NaN,NaN,NaN,NaN
3,2012-07-07,2667930.94,2108246.62,73,73,7,NaN,NaN,328.58,NaN,NaN,NaN,4.0
4,2012-07-08,2360851.90,1808622.79,88,87,7,NaN,NaN,428.18,NaN,NaN,NaN,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3828,2022-12-27,2100553.66,2184872.24,108,107,12,17416.0,62527.0,256.63,9.0,4.111111,26482.11,60.0
3829,2022-12-28,3448729.20,3513621.00,164,163,12,21071.0,67456.0,202.67,6.0,4.333333,97387.35,65.0
3830,2022-12-29,3083944.33,3170787.10,143,143,12,20884.0,82155.0,211.90,10.0,3.700000,20897.84,66.0
3831,2022-12-30,2884668.76,3022292.15,106,106,12,17679.0,79308.0,NaN,18.0,4.166667,43613.12,51.0
3832,2022-12-31,2383037.48,2279288.13,74,74,12,21743.0,94844.0,NaN,18.0,3.833333,97557.23,61.0

In [45]:
cols_to_fill = ['sum_of_sessions', 'sum_of_page_views', 'sum_of_shipping_fee', 'number_visitor_review', 'mean_of_rating', 'sum_of_refund', 'number_of_customer_signup']

# Fill tất cả trong 1 vòng lặp
for col in cols_to_fill:
    master_df[col] = master_df.groupby('month')[col].transform(
        lambda x: x.fillna(x.mean())
    )

master_df

,Date,Revenue,COGS,number_of_order,number_of_customer,month,sum_of_sessions,sum_of_page_views,sum_of_shipping_fee,number_visitor_review,mean_of_rating,sum_of_refund,number_of_customer_signup
0,2012-07-04,5123547.94,3982991.19,162,161,7,28192.158065,122409.558065,157.760000,36.592145,3.945572,157291.178061,3.000000
1,2012-07-05,2751773.45,2150580.23,97,97,7,28192.158065,122409.558065,172.750000,36.592145,3.945572,157291.178061,5.000000
2,2012-07-06,3054029.42,2517632.84,93,93,7,28192.158065,122409.558065,292.150000,36.592145,3.945572,157291.178061,30.964179
3,2012-07-07,2667930.94,2108246.62,73,73,7,28192.158065,122409.558065,328.580000,36.592145,3.945572,157291.178061,4.000000
4,2012-07-08,2360851.90,1808622.79,88,87,7,28192.158065,122409.558065,428.180000,36.592145,3.945572,157291.178061,4.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3828,2022-12-27,2100553.66,2184872.24,108,107,12,17416.000000,62527.000000,256.630000,9.000000,4.111111,26482.110000,60.000000
3829,2022-12-28,3448729.20,3513621.00,164,163,12,21071.000000,67456.000000,202.670000,6.000000,4.333333,97387.350000,65.000000
3830,2022-12-29,3083944.33,3170787.10,143,143,12,20884.000000,82155.000000,211.900000,10.000000,3.700000,20897.840000,66.000000
3831,2022-12-30,2884668.76,3022292.15,106,106,12,17679.000000,79308.000000,1060.007581,18.000000,4.166667,43613.120000,51.000000
3832,2022-12-31,2383037.48,2279288.13,74,74,12,21743.000000,94844.000000,1060.007581,18.000000,3.833333,97557.230000,61.000000

In [46]:
master_df.to_csv(os.path.join(PROCESSED_DIR, 'data_train.csv'), index=False)
print(" Hoàn thành: Đã làm sạch và gom tất cả về bảng data train !")

 Hoàn thành: Đã làm sạch và gom tất cả về bảng data train !